### ISSUE TITLE
Question: Do you plan to support HTTPS connections?

### ISSUE THREAD

**Issue by twata1** [shogo82148/p5-aws-lambda#108]
Hello,

Do you plan to support HTTPS connections?
(Personally, I would use HTTP-TLS Proxy.)

I am asking because I have seen the following.
https://github.com/chansen/p5-http-tiny/pull/151

I am sorry if you are offended.

Thank you,

**Comment by shogo82148** [comment]
AWS::Lambda is not affected by that issue because it does not perform HTTPS communication.
It communicates with AWS using a trusted route, so it communicates in plain text.

**Comment by twata1** [comment]
Thanks for your reply.

I am happy that AWS::Lambda is not affected by that issue.
Thank you very much!
