### ISSUE TITLE
Support AWS Lambda response streaming 

### ISSUE THREAD

**Issue by jwrightecs** [shogo82148/p5-aws-lambda#109]
AWS Lambda now supports response streaming

https://aws.amazon.com/blogs/compute/introducing-aws-lambda-response-streaming/

which implement's Node's writable stream API for the node api

https://nodejs.org/docs/latest-v14.x/api/stream.html#stream_writable_streams

which is a decent approximation of the PSGI delayed response / streaming body interface

**Comment by shogo82148** [comment]
AWS::Lambda now supports response streaming #117 
Enjoy!
