### ISSUE TITLE
Inject request id

### ISSUE THREAD

**Issue by pplu** [shogo82148/p5-aws-lambda#15]
Hi,

   https://metacpan.org/pod/Plack::Middleware::RequestId injects a `psgix.request_id` field in the environment to uniquely identify requests. I think it would be interesting for AWS::Lambda::PSGI to put the request id in the Lambda event into the `psgix.request_id` field, as other middlewares later can use that value.

   What do you think?

**Comment by shogo82148** [comment]
AWS::Lambda 0.0.7 injects the request id, enjoy!
https://metacpan.org/release/SHOGO/AWS-Lambda-0.0.7

**Comment by pplu** [comment]
:dancer:
