### ISSUE TITLE
Include Paws 

### ISSUE THREAD

**Issue by henrikbjorn** [shogo82148/p5-aws-lambda#22]
It is normal for runtimes to include the AWS SDK. For perl it seems it is Paws.

**Comment by shogo82148** [comment]
I looks good. I'll try it.

**Comment by shogo82148** [comment]
I published AWS::Lambda 0.0.6 and Paws layers.

- https://metacpan.org/pod/release/SHOGO/AWS-Lambda-0.0.6/lib/AWS/Lambda.pm
