### ISSUE TITLE
Making Paws layer smaller

### ISSUE THREAD

**Issue by pplu** [shogo82148/p5-aws-lambda#31]
Hi,

   I thought I would share with you how I've made smaller Paws installations (for smaller Docker images, for example). Maybe this is useful for your Paws layer generation.

I found an option in cpanm to not generate man pages.
```
cpanm -l local -n --installdeps --no-man-pages . 
```
Stripping out all the POD in the modules also reduces a lot of used space. I have a small script which you may want to use:
```
curl -s https://raw.githubusercontent.com/pplu/p5-pod-stripper/feature/fatpack/fatpacked/pod_stripper.pl | perl - /path/to/local/lib/perl5
```
Hope it helps!

**Comment by shogo82148** [comment]
I made smaller layers using `pod_stripper.pl`, and released it as AWS::Lambda 0.0.10 https://metacpan.org/pod/release/SHOGO/AWS-Lambda-0.0.10/lib/AWS/Lambda.pm
The runtime size is reduced from 66MB to 52MB (unzipped), from 17.5 MB to 12.9 MB (zipped).
The Paws modules size is reduced from 118MB to 87MB (unzipped), from 25.6 MB to 10.7 MB (zipped).

https://github.com/shogo82148/p5-aws-lambda/pull/32#issuecomment-533786032

Thank you for your information!
