### ISSUE TITLE
Issue with Nodejs 10.x runtime

### ISSUE THREAD

**Issue by juliendangers** [shogo82148/p5-aws-lambda#36]
Hello,

When trying to update Nodejs runtime to 10.x or 12.x we run into the following issue:

`perl: error while loading shared libraries: libcrypt.so.1: cannot open shared object file: No such file or directory`

We've been testing with `arn:aws:lambda:REGION:445285296882:layer:perl-5-30-runtime:X` (all versions) and `arn:aws:lambda:REGION:445285296882:layer:perl-5-28-runtime:12`

Would you have any idea why ?

Thanks

**Comment by shogo82148** [comment]
the perl layers are not compatible with the Nodejs runtimes.
your function's runtime must be `provided` ref. https://docs.aws.amazon.com/lambda/latest/dg/runtimes-custom.html

because a custom runtime runs on Amazon Linux, while the Nodejs runtimes run on Amazon Linux 2.

**Comment by juliendangers** [comment]
I see, thank you for your help

**Comment by juliendangers** [comment]
I see, thank you for your help
