### ISSUE TITLE
Paws layer missing Net::SSLeay & IO::Socket::SSL

### ISSUE THREAD

**Issue by vlashef** [shogo82148/p5-aws-lambda#75]
Hi There!

About 2 weeks ago a perl lambda I had running decided to stop. after some investigating it looks like for some reason  2 libraries are not installed:

Would it be possible to add these into the paws lambda layer?

  "errorMessage": "IO::Socket::SSL 1.42 must be installed for https support\nNet::SSLeay 1.49 must be installed for https support\n\n\nTrace begun at /opt/lib/perl5/site_perl/5.34.0/Paws/Net/RetryCallerRole.pm line 19\nPaws::Net::RetryCallerRole::do_call('Paws::Net::Caller=HASH(0x1f876880)', 'Paws::STS=HASH(0x1fbfe918)', 'Paws::STS::GetCallerIdentity=HASH(0x2001d830)') called at /opt/lib/perl5/site_perl/5.34.0/Paws/STS.pm line 92\nPaws::STS::GetCallerIdentity('Paws::STS=HASH(0x1fbfe918)') called at /var/task/myscript.pl line 16\nmain::get_aws_account at /var/task/myscript.pl line 260\nmain::handle at /var/task/myscript.pl line 321\nrequire /var/task/myscript.pl at /opt/lib/perl5/vendor_perl/5.34.0/AWS/Lambda/Bootstrap.pm line 70\nAWS::Lambda::Bootstrap::try {...}  at /opt/lib/perl5/vendor_perl/5.34.0/Try/Tiny.pm line 100\neval {...} at /opt/lib/perl5/vendor_perl/5.34.0/Try/Tiny.pm line 93\nTry::Tiny::try('CODE(0x1d3b68a8)', 'Try::Tiny::Catch=REF(0x1d3a37c8)') called at /opt/lib/perl5/vendor_perl/5.34.0/AWS/Lambda/Bootstrap.pm line 77\nAWS::Lambda::Bootstrap::_init('AWS::Lambda::Bootstrap=HASH(0x1d3b6800)') called at /opt/lib/perl5/vendor_perl/5.34.0/AWS/Lambda/Bootstrap.pm line 53\nAWS::Lambda::Bootstrap::handle_events('AWS::Lambda::Bootstrap=HASH(0x1d3b6800)') called at /opt/lib/perl5/vendor_perl/5.34.0/AWS/Lambda/Bootstrap.pm line 21\nAWS::Lambda::Bootstrap::bootstrap at /opt/bootstrap line 8\nCompilation failed in require at /opt/lib/perl5/vendor_perl/5.34.0/AWS/Lambda/Bootstrap.pm line 70.\n"

Thank you for the awesome library/code/guidance on how to set these up. I hope you can fix it so others don't run into this problem also!
Cheers!

**Comment by shogo82148** [comment]
Can I have the version of layers you are using?

**Comment by vlashef** [comment]
Thank you for looking into this!

arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-34-runtime-al2-x86_64:2
arn:aws:lambda:ap-southeast-2:445285296882:layer:perl-5-34-paws-al2-x86_64:2

Are the 2 being used.

**Comment by vlashef** [comment]
I tried all the other combinations also and was not having any luck either, and was using the amazon linux 2 'custom' runtime
